### ISSUE TITLE
e.POST panics on redirect

### ISSUE THREAD

**Issue by EtienneBruines** [gavv/httpexpect#9]
Minimal example:

```go
func TestMinimal(t *testing.T) {
	iris.Post("/test-minimal-post", func(c *iris.Context) {
		c.Redirect("/", iris.StatusFound)
	})

	e := httpexpect.WithConfig(httpexpect.Config{
//		BaseURL:  "http://example.com", // this line makes no difference
		Reporter: httpexpect.NewAssertReporter(t),
		Client: &http.Client{
			Transport: httpexpect.NewFastBinder(iris.NoListen().Handler),
			Jar:       httpexpect.NewJar(),
		},
	})

	e.POST("/test-minimal-post").
		Expect()
}
```

It seems that the `http.Client` panics whenever the server responds with a redirect, as a response to `POST`. 

Example panic:

```
--- FAIL: TestLogin (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x483e4e]

goroutine 9 [running]:
panic(0x9abca0, 0xc42000c0d0)
        /home/etiennebruines/workspaces/go-master/src/runtime/panic.go:500 +0x1a1
testing.tRunner.func1(0xc420092300)
        /home/etiennebruines/workspaces/go-master/src/testing/testing.go:579 +0x25d
panic(0x9abca0, 0xc42000c0d0)
        /home/etiennebruines/workspaces/go-master/src/runtime/panic.go:458 +0x243
io.(*LimitedReader).Read(0xc4202a6b20, 0xc4202be000, 0x2000, 0x2000, 0x411505, 0xc420095948, 0x18)
        /home/etiennebruines/workspaces/go-master/src/io/io.go:436 +0x4e
io/ioutil.devNull.ReadFrom(0x0, 0xd1c800, 0xc4202a6b20, 0x9b5f40, 0xaa7401, 0x7f80f5181258)
        /home/etiennebruines/workspaces/go-master/src/io/ioutil/ioutil.go:151 +0x85
io/ioutil.(*devNull).ReadFrom(0xc42000c610, 0xd1c800, 0xc4202a6b20, 0xc420051bb8, 0x1, 0x18)
        <autogenerated>:9 +0x66
io.copyBuffer(0xd1e000, 0xc42000c610, 0xd1c800, 0xc4202a6b20, 0x0, 0x0, 0x0, 0x9d05c0, 0xa47b01, 0xc4202a6b20)
        /home/etiennebruines/workspaces/go-master/src/io/io.go:384 +0x324
io.Copy(0xd1e000, 0xc42000c610, 0xd1c800, 0xc4202a6b20, 0x1, 0x1, 0x0)
        /home/etiennebruines/workspaces/go-master/src/io/io.go:360 +0x68
io.CopyN(0xd1e000, 0xc42000c610, 0x0, 0x0, 0x800, 0x0, 0x0, 0x0)
        /home/etiennebruines/workspaces/go-master/src/io/io.go:336 +0x8c
net/http.(*Client).doFollowingRedirects(0xc4202b6060, 0xc4201ace60, 0xaaa910, 0x4, 0x45eb01, 0x25ce)
        /home/etiennebruines/workspaces/go-master/src/net/http/client.go:510 +0x527
net/http.(*Client).Do(0xc4202b6060, 0xc4201ace60, 0x0, 0x0, 0x0)
        /home/etiennebruines/workspaces/go-master/src/net/http/client.go:187 +0x11d
github.com/gavv/httpexpect.(*Request).sendRequest(0xc4201ace00, 0x7, 0x0)
        /home/etiennebruines/workspaces/go/src/github.com/gavv/httpexpect/request.go:699 +0xed
github.com/gavv/httpexpect.(*Request).Expect(0xc4201ace00, 0xa47787)
        /home/etiennebruines/workspaces/go/src/github.com/gavv/httpexpect/request.go:655 +0x39
bitbucket.org/impprog/pes/controllers.TestLogin(0xc420092300)
        /home/etiennebruines/workspaces/go/src/bitbucket.org/impprog/pes/controllers/login_test.go:23 +0xe3
testing.tRunner(0xc420092300, 0xaa9650)
        /home/etiennebruines/workspaces/go-master/src/testing/testing.go:610 +0x81
created by testing.(*T).Run
        /home/etiennebruines/workspaces/go-master/src/testing/testing.go:646 +0x2ec
```

**Comment by gavv** [comment]
Should be fixed in current `master` (not pushing to `v1` for now).

**Comment by EtienneBruines** [comment]
Confirmed. Thank you @gavv for your awesome work :smile:

**Comment by gavv** [comment]
Good.

/link #7
